# Generated by Django 4.2.3 on 2023-12-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='classRoom',
        ),
    ]
