# Generated by Django 4.2.3 on 2023-12-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_email_student_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classRoom',
        ),
        migrations.AddField(
            model_name='student',
            name='classR',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
