# Generated by Django 4.2.3 on 2023-12-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ManyToManyField(related_name='subject', to='app.category'),
        ),
    ]
