# Generated by Django 4.2.3 on 2023-12-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_rate_subject_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='slot',
        ),
        migrations.AddField(
            model_name='student',
            name='slot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
