# Generated by Django 4.2.3 on 2024-01-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
