# Generated by Django 4.2.3 on 2024-01-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classRoom',
        ),
        migrations.AddField(
            model_name='student',
            name='classRoom',
            field=models.ManyToManyField(related_name='classname', to='app.classname'),
        ),
    ]
