# Generated by Django 4.2.3 on 2024-01-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_student_classroom_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='app.classname'),
        ),
    ]
