# Generated by Django 4.2.3 on 2024-01-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_classname_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='students',
        ),
        migrations.AlterField(
            model_name='student',
            name='classRoom',
            field=models.ManyToManyField(related_name='student', to='app.category'),
        ),
    ]
