# Generated by Django 4.2.3 on 2024-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_classname_students_alter_student_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classRoom',
            field=models.ManyToManyField(related_name='student', to='app.classname'),
        ),
    ]
