# Generated by Django 4.2.3 on 2024-01-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
