# Generated by Django 4.2.3 on 2024-01-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='regissubjectitem',
            name='descriptionSubjectItem',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
