# Generated by Django 4.2.3 on 2024-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_regissubjectitem_descriptionsubjectitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
