# Generated by Django 4.2.3 on 2024-01-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='lessons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
