# Generated by Django 4.2.3 on 2024-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_subject_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='lessons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
