# Generated by Django 4.2.3 on 2024-01-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_subject_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='lessons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
