# Generated by Django 4.2.3 on 2024-01-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_lesson_image_alter_lesson_content_alter_lesson_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='image',
            new_name='content_image',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='content',
            new_name='content_text',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
