# Generated by Django 4.2.3 on 2024-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='danh_hieu',
            field=models.ImageField(blank=True, null=True, upload_to='student_danh_hieu/'),
        ),
    ]
