# Generated by Django 4.2.3 on 2024-03-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_student_danh_hieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='student_uploads/'),
        ),
    ]
